### ISSUE TITLE
what does __JNI.TOP() in sample means？

### ISSUE THREAD

**Issue by DenverBYF** [SunghoLee/c-summary#14]
import __Model.*;

public class Main_ {
  public int intMethod(int i) {
    return (Integer)__JNI.TOP();
  }
}

when I try to learn about you paper, I got a question, in your sample, sample.c will transfer to Main.java. but in Main.java, I dot't what does __JNI.TOP() means, in __Model/__JNI.java I can't find a function called TOP();

**Comment by SunghoLee** [comment]
The __JNI.TOP() means that it cannot be abstracted as a value or symbol. We can think of it as "Top" in abstract interpretation. Does it make sense?

**Comment by anabioticsoul** [comment]
I have a question that the __JNI.TOP() method have no definition. I want to use WALA to construct the call graph, but the source code cannot be compiled with this error. How can I solve this problem? Thanks a lot!

**Comment by anabioticsoul** [comment]
> The __JNI.TOP() means that it cannot be abstracted as a value or symbol. We can think of it as "Top" in abstract interpretation. Does it make sense?

I have a question that the __JNI.TOP() method have no definition. I want to use WALA to construct the call graph, but the source code cannot be compiled with this error. How can I solve this problem? Thanks a lot!

**Comment by SunghoLee** [comment]
Sorry for the late response.

We designed the __JNI.TOP() method as an opaque function. The modified FlowDroid takes both an APK and generated source files from the C-Summary, translates the source files to bytecode, and injects methods in the bytecode. Thus, we didn't need the compilation process. Since the __JNI.TOP() is an opaque function, the modified FlowDroid just understands that the function returns a TOP abstract value. 

If you want to compile the source files generated from the C-Summary, you need to define the __JNI.TOP(). The definition may like the follow:
`public static java.lang.Object TOP() { return null; }` 
After then, modify WALA to handle the function call as an opaque function returning the TOP value in your abstract domain.

Is this information helpful for you?

**Comment by SunghoLee** [comment]
Close this issue.

**Comment by anabioticsoul** [comment]
Ok, That's pretty helpful, thank you very much!
